version: '3.8'
services:
  xray:
    build:
      context: ./xray/docker
      args:
        - version=v1.5.3
        - timezone=<your timezone>
    network_mode: "host"
    volumes:
      - ./xray/config.json:/etc/xray/config.json
    restart: unless-stopped
  caddy:
    build:
      context: ./caddy/docker
      args:
        - version=2.4.6
        - timezone=<your timezone>
    network_mode: "host"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/www:/etc/caddy/www
      - caddy_data:/data
    environment:
      - HTTPS_ADDRESS=https://<Your domain>:443
      - CLOUDFLARE_API_TOKEN=<API token from Cloudflare>
    restart: unless-stopped
volumes:
  caddy_data:
