version: '3.8'
services:

  xray:
    build:
      context: ./xray/docker
      args:
        - version=v1.1.4
        - timezone=Asia/Tokyo
    network_mode: "bridge"
    links:
      - "caddy"
    ports:
      - "443:443"
    volumes:
      - ./xray/config.json:/etc/xray/config.json
      - caddy_data:/data
    restart: unless-stopped

  caddy:
    build:
      context: ./caddy/docker
      args:
        - version=2.3.0
    network_mode: "bridge"
    ports:
      - "8443:8443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - SITE_ADDRESS=<your domain:8443>
      - CLOUDFLARE_API_TOKEN=<API token from Cloudflare>
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
